[package]
name = "powhasher"
version = "0.2.0"
authors = ["Kaz Wesley <keziahw@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
core_affinity = "0.5.9"
failure = "0.1.1"
generic-array = "0.11.0"
serde = "1.0.34"
serde_derive = "1.0.34"
serde_json = "1.0.5"
env_logger = "0.5.10"
log = "0.4.2"
arrayvec = { version = "0.4.6", features = ["serde-1"] }
typenum = "1.9.0"
clap = "2.27.0"

[dependencies.cryptonight]
path = "cryptonight"
version = "0.1.0"

# debuggable release mode
[profile.release]
debug = true
debug-assertions = true

# fast release mode
#[profile.release]
# lto = true
